// apps/zbugs/src/main.tsx
import {StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import 'react-toastify/dist/ReactToastify.css';
import {must} from '../../../packages/shared/src/must.js';
import {LoginProvider} from './components/login-provider.tsx';
import './index.css';
import {Root} from './root.tsx';
import {ZeroInit} from './zero-init.tsx';

createRoot(must(document.getElementById('root'))).render(
  <LoginProvider>
    <StrictMode>
      <ZeroInit>
        <Root />
      </ZeroInit>
    </StrictMode>
  </LoginProvider>,
);

// apps/zbugs-lite-solid/src/index.tsx
import {render} from 'solid-js/web';
import {App} from './App.tsx';
import './index.css';
import {LoginProvider} from './login-provider.tsx';
import {ZeroInit} from './zero-init.tsx';

const root = document.getElementById('root');

if (!root) {
  throw new Error('Root element not found');
}

render(
  () => (
    <LoginProvider>
      <ZeroInit>
        <App />
      </ZeroInit>
    </LoginProvider>
  ),
  root,
);
