// packages/zero-react/src/use-zero.tsx
import {createContext, useContext} from 'react';
import type {Zero} from '../../zero-client/src/mod.js';
import type {Schema} from '../../zero-schema/src/mod.js';

// eslint-disable-next-line @typescript-eslint/naming-convention
const ZeroContext = createContext<unknown | undefined>(undefined);

export function useZero<S extends Schema, Z extends Zero<S> = Zero<S>>(): Z {
  const zero = useContext(ZeroContext);
  if (zero === undefined) {
    throw new Error('useZero must be used within a ZeroProvider');
  }
  return zero as Z;
}

export function createUseZero<S extends Schema, Z extends Zero<S> = Zero<S>>() {
  return () => useZero<S, Z>();
}

export function ZeroProvider<S extends Schema, Z extends Zero<S> = Zero<S>>({
  children,
  zero,
}: {
  children: React.ReactNode;
  zero: Z;
}) {
  return <ZeroContext.Provider value={zero}>{children}</ZeroContext.Provider>;
}

// packages/zero-solid/src/use-zero.tsx
import {batch, createContext, createMemo, useContext, type JSX} from 'solid-js';
import {
  Zero,
  type CustomMutatorDefs,
  type Schema,
  type ZeroOptions,
} from '../../zero/src/zero.ts';

// eslint-disable-next-line @typescript-eslint/naming-convention, @typescript-eslint/no-explicit-any
export const ZeroContext = createContext<(() => Zero<any, any>) | undefined>(
  undefined,
);

export function createZero<S extends Schema, MD extends CustomMutatorDefs<S>>(
  options: ZeroOptions<S, MD>,
): Zero<S, MD> {
  const opts = {
    ...options,
    batchViewUpdates: batch,
  };
  return new Zero(opts);
}

export function useZero<
  S extends Schema,
  MD extends CustomMutatorDefs<S> | undefined = undefined,
>(): () => Zero<S, MD> | undefined {
  const zero = useContext(ZeroContext);

  // TODO: uncomment when we require ZeroProvider in a future release.
  // if (zero === undefined) {
  //   throw new Error('useZero must be used within a ZeroProvider');
  // }
  return zero ?? (() => undefined);
}

export function createUseZero<
  S extends Schema,
  MD extends CustomMutatorDefs<S> | undefined = undefined,
>() {
  return () => useZero<S, MD>();
}

export function ZeroProvider<
  S extends Schema,
  MD extends CustomMutatorDefs<S> | undefined = undefined,
>(props: {
  children: JSX.Element;
  zeroSignal: () => ZeroOptions<S, MD> | {zero: Zero<S, MD>};
}) {
  const zero = createMemo(() => {
    const z = props.zeroSignal();
    if ('zero' in z) {
      return z.zero;
    }
    return new Zero({
      ...z,
      batchViewUpdates: batch,
    });
  });

  return (
    <ZeroContext.Provider value={zero}>{props.children}</ZeroContext.Provider>
  );
}
