// packages/zero-react/src/use-zero-connection-state.tsx
import {useSyncExternalStore} from 'react';
import type {ConnectionState} from '../../zero/src/zero.ts';
import {useZero} from './zero-provider.tsx';

/**
 * Hook to subscribe to the connection status of the Zero instance.
 *
 * @returns The connection status of the Zero instance.
 * @see {@link ConnectionState} for more details on the connection state.
 */
export function useZeroConnectionState(): ConnectionState {
  const zero = useZero();
  return useSyncExternalStore(
    zero.connection.state.subscribe,
    () => zero.connection.state.current,
    () => zero.connection.state.current,
  );
}

// packages/zero-solid/src/use-zero-connection-state.ts
import {createEffect, createSignal, onCleanup, type Accessor} from 'solid-js';
import type {ConnectionState} from '../../zero/src/zero.ts';
import {useZero} from './use-zero.ts';

/**
 * Tracks the connection status of the current Zero instance.
 *
 * @returns The connection status of the Zero instance.
 * @see {@link ConnectionState} for more details on the connection state.
 */
export function useZeroConnectionState(): Accessor<ConnectionState> {
  const zero = useZero();

  const [connectionState, setConnectionState] = createSignal<ConnectionState>(
    zero().connection.state.current,
  );

  createEffect(() => {
    const unsubscribe = zero().connection.state.subscribe(setConnectionState);

    onCleanup(unsubscribe);
  });

  return connectionState;
}
