// apps/zbugs-lite-solid/src/zero-init.tsx
import { ZeroProvider } from '@rocicorp/zero/solid';
import type { JSX } from 'solid-js';
import { useLogin } from './login-provider.tsx';
import { mutators, schema } from './zero.ts';

export function ZeroInit(props: {children: JSX.Element}) {
  const cacheURL = import.meta.env.VITE_PUBLIC_SERVER;
  const login = useLogin();
  const loginState = login.loginState();

  console.log('[ZeroInit] cacheURL:', cacheURL);
  console.log('[ZeroInit] schema tables:', Object.keys(schema.tables));
  console.log('[ZeroInit] loginState:', loginState);

  return (
    <ZeroProvider
      schema={schema}
      mutators={mutators}
      cacheURL={cacheURL}
      userID={loginState?.decoded?.sub ?? 'anon'}
      logLevel="debug"
      mutateURL="http://localhost:5173/api/mutate"
      queryURL="http://localhost:5173/api/query"
      auth={loginState?.encoded}
      context={loginState?.decoded}
    >
      {props.children}
    </ZeroProvider>
  );
}

// apps/zbugs/src/zero-init.tsx
import {type ReactNode} from 'react';
import {mutators} from '../shared/mutators.ts';
import {schema} from '../shared/schema.ts';
import {useLogin} from './hooks/use-login.tsx';
import {ZeroProvider} from '@rocicorp/zero/react';

export function ZeroInit({children}: {children: ReactNode}) {
  const login = useLogin();

  return (
    <ZeroProvider
      schema={schema}
      server={import.meta.env.VITE_PUBLIC_SERVER}
      userID={login.loginState?.decoded?.sub ?? 'anon'}
      mutators={mutators}
      logLevel="info"
      auth={login.loginState?.encoded}
      mutateURL={`${window.location.origin}/api/mutate`}
      getQueriesURL={`${window.location.origin}/api/get-queries`}
      context={login.loginState?.decoded}
    >
      {children}
    </ZeroProvider>
  );
}
